services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    command: uvicorn main:app --host 0.0.0.0 --port 8070 --reload
    container_name: edtech-lite-api
    ports:
      - "8070:8070"
    env_file:
      - ../.env.local
    volumes:
      - ..:/app
    depends_on:
      - mysql
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mysql:
    image: mysql:8
    container_name: edtech-lite-mysql
    env_file:
      - ../.env.local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adtech_lite_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    container_name: edtech-lite-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
